import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import cn from 'clsx'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`, 'flex flex-col items-center justify-center h-screen w-screen')}
      >
        <div className='flex items-center gap-3 absolute top-5'>
          <img src="/Header logo.svg" alt="" />
          <span className='text-3xl font-bold'>WEATHER</span>
        </div>
        {children}
      </body>
    </html>
  );
}
